/**
 * @description - The head component.
 * @return {JSX.Element} - The head component.
 */
export default function Head() {
  return (
    <>
      <title>Page</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta content='Generated by create next app' name='description' />
      <link href='/favicon.ico' rel='icon' />
    </>
  );
}
